---
title: "Data Manipulation using dplyr"
author: "alexmerk"
date: "December, 2018"
output: rmarkdown::github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Introduction to dplyr and tbl
### 1.1 Reading the data set as a tibble
```{r practice 1.1}

# Load the dplyr package
library(dplyr)

# Load the hflights package
#install.packages("hflights")
library(hflights)

# Call both head() and summary() on hflights
#head(hflights)
#summary(hflights)

# Convert the hflights_df data.frame into a hflights tbl
hflights <- tbl_df(hflights)

# Display the hflights tbl
hflights
glimpse(hflights)

# Create the object carriers
carriers <- hflights$UniqueCarrier
```

### 1.2 Changing labels of hflights
```{r practice 1.2}
# Both the dplyr and hflights packages are loaded into workspace
lut <- c("AA" = "American", "AS" = "Alaska", "B6" = "JetBlue", "CO" = "Continental", 
         "DL" = "Delta", "OO" = "SkyWest", "UA" = "United", "US" = "US_Airways", 
         "WN" = "Southwest", "EV" = "Atlantic_Southeast", "F9" = "Frontier", 
         "FL" = "AirTran", "MQ" = "American_Eagle", "XE" = "ExpressJet", "YV" = "Mesa")

# Add the Carrier column to hflights
## lut is a vector with the coding scheme, also the "lookup table". The vector in brackets (UniqueCarrier) is the vector to be transformed.
hflights$Carrier <- lut[hflights$UniqueCarrier]

# Glimpse at hflights
glimpse(hflights)

# The hflights tbl you built in the previous exercise is available in the workspace.

# The lookup table
lut <- c("A" = "carrier", "B" = "weather", "C" = "FFA", "D" = "security", "E" = "not cancelled")

# Add the Code column
hflights$Code <- lut[hflights$CancellationCode]

# Glimpse at hflights
glimpse(hflights)
```

