---
title: "DataCamp - EDA Case Study"
author: "alexmerk"
date: "December 12, 2018"
output: html_document
---

```{r setup, include=FALSE, cache=TRUE}
knitr::opts_chunk$set(echo = TRUE)

# Installing the packages
library(pacman)
pacman::p_load(dplyr, ggplot2, countrycode, broom, purrr, tidyr)

# Importing the data set
votes <- as_tibble(read.csv(
    file="https://github.com/alexmerk/xcourse/raw/master/datacamp_eda/votes.csv"))
```

1 Data cleaning and summarizing with dplyr
```{r dplyr}
# Filter for votes that are "yes", "abstain", or "no"
# Add another %>% step to add a year column
votes %>%
  filter(vote <= 3) %>%
  mutate(year=session+1945)

# Load the countrycode package
#library(countrycode)

# Convert country code 100
countrycode(100,"cown","country.name")

# Add a country column within the mutate: votes_processed
votes_processed <- votes %>%
  filter(vote <= 3) %>%
  mutate(year = session + 1945, 
  country=countrycode(ccode,"cown","country.name"))

# Find total and fraction of "yes" votes
votes_processed %>% summarize(
total=n(),
percent_yes=mean(vote==1))

# Summarize by country: by_country
by_country <- votes_processed %>%
  group_by(country) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))

# Filter out countries with fewer than 100 votes
by_country %>%
  arrange(percent_yes) %>%
  filter(total>=100)
  
```

2 Visualizing data with ggplot2
```{r ggplot2}
# Define by_year
by_year <- votes_processed %>%
  group_by(year) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))

# Load the ggplot2 package
#library(ggplot2)

# Create line plot
ggplot(by_year, aes(x=year, y=percent_yes)) +
  geom_line()

# Change to scatter plot and add smoothing curve
ggplot(by_year, aes(year, percent_yes)) +
  geom_point() + geom_smooth()
  
# Group by year and country: by_year_country
by_year_country <- votes_processed %>%
  group_by(year, country) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))

# Start with by_year_country dataset
by_year_country <- votes_processed %>%
  group_by(year, country) %>%
  summarize(total = n(),
            percent_yes = mean(vote == 1))

# Print by_year_country
by_year_country

# Create a filtered version: UK_by_year
UK_by_year <- filter(by_year_country, country=="United Kingdom")

# Line plot of percent_yes over time for UK only
ggplot(UK_by_year, aes(x=year,y=percent_yes)) +
  geom_line()

# Vector of four countries to examine
countries <- c("United States", "United Kingdom",
               "France", "India")

# Filter by_year_country: filtered_4_countries
filtered_4_countries <- by_year_country %>%
filter(country %in% countries)

# Line plot of % yes in four countries
ggplot(filtered_4_countries, aes(x=year, y=percent_yes, color=country)) +
  geom_line()

# Vector of six countries to examine
countries <- c("United States", "United Kingdom",
               "France", "Japan", "Brazil", "India")

# Filtered by_year_country: filtered_6_countries
filtered_6_countries <- by_year_country %>% filter (country %in% countries)

# Line plot of % yes over time faceted by country
ggplot(filtered_6_countries, aes(x=year, y=percent_yes)) +
geom_line() +
  facet_wrap(~country)


# Line plot of % yes over time faceted by country and a free y-scale
ggplot(filtered_6_countries, aes(year, percent_yes)) +
  geom_line() +
  facet_wrap(~ country, scales="free_y")

# Add three more countries to this list
countries <- c("United States", "United Kingdom",
               "France", "Japan", "Brazil", "India", 
               "Russian Federation", "Pakistan", "Kazakhstan")

# Filtered by_year_country: filtered_countries
filtered_countries <- by_year_country %>%
  filter(country %in% countries)

# Line plot of % yes over time faceted by country
ggplot(filtered_countries, aes(year, percent_yes)) +
  geom_line() +
  facet_wrap(~ country, scales = "free_y")
```

3 Tidy modeling with broom
```{r broom}
# Percentage of yes votes from the US by year: US_by_year
US_by_year <- by_year_country %>%
  filter(country == "United States")

# Print the US_by_year data
US_by_year

# Perform a linear regression of percent_yes by year: US_fit
US_fit <- lm(formula=percent_yes ~ year, data=US_by_year)

# Perform summary() on the US_fit object
summary(US_fit)

# Load the broom package
#library(broom)

# Call the tidy() function on the US_fit object
tidy(US_fit)


# Linear regression of percent_yes by year for US
US_by_year <- by_year_country %>%
  filter(country == "United States")
US_fit <- lm(percent_yes ~ year, US_by_year)

# Fit model for the United Kingdom
UK_by_year <- by_year_country %>%
filter(country=="United Kingdom")
UK_fit <- lm(percent_yes ~ year, UK_by_year)

# Create US_tidied and UK_tidied
US_tidied <- tidy(US_fit)
UK_tidied <- tidy(UK_fit)

# Combine the two tidied models
bind_rows(US_tidied, UK_tidied)

#######################
### Nesting the data ##
#######################
# Load the tidyr package
#library(tidyr)

# Nest all columns besides country
by_year_country %>% nest(-c(country))

# All countries are nested besides country
nested <- by_year_country %>%
  nest(-country)

# Print the nested data for Brazil
nested$data[nested$country=="Brazil"]

# Unnest the data column to return it to its original form
nested %>% unnest(data)

# Load tidyr and purrr
#library(tidyr)
#library(purrr)


# Perform a linear regression on each item in the data column
by_year_country %>%
  nest(-country) %>% mutate(model=map(data, ~ lm(percent_yes ~ year, .)))
  
# Load the broom package
#library(broom)

# Add another mutate that applies tidy() to each model
by_year_country %>%
  nest(-country) %>%
  mutate(model = map(data, ~ lm(percent_yes ~ year, data = .))) %>%
  mutate(tidied = map(model, ~tidy(.)))

# Add one more step that unnests the tidied column
country_coefficients <- by_year_country %>%
  nest(-country) %>%
  mutate(model = map(data, ~ lm(percent_yes ~ year, data = .)),
         tidied = map(model, tidy)) %>%
         unnest(tidied)

# Print the resulting country_coefficients variable
country_coefficients


### Working with many tidy models ###
# Print the country_coefficients dataset
country_coefficients

# Filter for only the slope terms
filter(country_coefficients, term=="year")

# Filter for only the slope terms
slope_terms <- country_coefficients %>%
  filter(term == "year")

# Add p.adjusted column, then filter
slope_terms %>% mutate (p.adjusted=p.adjust(p.value)) %>%
filter(p.adjusted <0.5)

# Filter by adjusted p-values
filtered_countries <- country_coefficients %>%
  filter(term == "year") %>%
  mutate(p.adjusted = p.adjust(p.value)) %>%
  filter(p.adjusted < .05)

# Sort for the countries increasing most quickly
arrange(filtered_countries, estimate)

# Sort for the countries decreasing most quickly
arrange(filtered_countries, desc(estimate))
```


